### ISSUE TITLE
Optimize Our Website

### ISSUE THREAD

**Issue by chenhoward** [rails-decal/railsdecal.com#163]
Slow initial loading time.

https://developers.google.com/speed/pagespeed/insights/?url=railsdecal.com

**Comment by helloramon** [comment]
Sent a PR in optimizing the images :smile: 

On a side note, I think it's cool you all are teaching RoR. Nothing like that here in SoCal as far as traditional schooling goes. 

Hopefully the PR helps, will look to lend a hand wherever I can.

**Comment by chenhoward** [comment]
Thanks @helloramon your PR was great!
